name: Fly Deploy Staging

on:
  push:
    branches:
      - staging

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: 'deploy --config ./fly.staging.toml --build-arg REMIX_TOKEN=${{ secrets.REMIX_TOKEN }} --build-arg DATABASE_URL="file:./dev.db?connection_limit=1" --build-arg REPO=${{ secrets.REPO }} --build-arg REPO_DOCS_PATH=${{ secrets.REPO_DOCS_PATH }} --build-arg REPO_LATEST_BRANCH=${{ secrets.REPO_LATEST_BRANCH }}'
