name: 🥺 No Response

on:
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: "5 * * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'remix-run/react-router-website'
    runs-on: ubuntu-latest
    steps:
      - name: 🥺 Handle Ghosting
        uses: actions/stale@v8
        with:
          close-issue-message: >
            This issue has been automatically closed because we haven't received a
            response from the original author 🙈. This automation helps keep the issue
            tracker clean from issues that aren't actionable. Please reach out if you
            have more information for us! 🙂
          close-pr-message: >
            This PR has been automatically closed because we haven't received a
            response from the original author 🙈. This automation helps keep the issue
            tracker clean from PRs that aren't actionable. Please reach out if you
            want to resume the work on this PR! 🙂
          # don't automatically mark issues/PRs as stale
          days-before-stale: -1
          stale-issue-label: needs-response
          stale-pr-label: needs-response
